"""create audio recordings transcripts and segments

Revision ID: adf9c60d178d
Revises: 6ca666161c77
Create Date: 2026-10-04 00:55:09.184727

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "adf9c60d178d"
down_revision: str | None = "6ca666161c77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_recordings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["interview_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_audio_recordings_session_id"), "audio_recordings", ["session_id"], unique=False
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("audio_recording_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_recording_id"], ["audio_recordings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcripts_audio_recording_id"),
        "transcripts",
        ["audio_recording_id"],
        unique=False,
    )
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=200), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_segments_transcript_id"),
        "transcript_segments",
        ["transcript_id"],
        unique=False,
    )
    op.add_column(
        "interview_messages",
        sa.Column("source", sa.String(length=32), server_default="text", nullable=False),
    )
    op.add_column(
        "interview_messages", sa.Column("transcript_segment_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_interview_messages_transcript_segment_id"),
        "interview_messages",
        ["transcript_segment_id"],
        unique=False,
    )
    op.create_foreign_key(
        "interview_messages_transcript_segment_id_fkey",
        "interview_messages",
        "transcript_segments",
        ["transcript_segment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "interview_messages_transcript_segment_id_fkey",
        "interview_messages",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_interview_messages_transcript_segment_id"), table_name="interview_messages"
    )
    op.drop_column("interview_messages", "transcript_segment_id")
    op.drop_column("interview_messages", "source")
    op.drop_index(op.f("ix_transcript_segments_transcript_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_transcripts_audio_recording_id"), table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index(op.f("ix_audio_recordings_session_id"), table_name="audio_recordings")
    op.drop_table("audio_recordings")
    # ### end Alembic commands ###
